language: go

env:
  - GO111MODULES=on

go:
  - 1.12.x

services:
  - docker

before_script:
  # linters
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  # test setup
  - make dev


script:
  - golangci-lint run -v
  - go test -v -race ./...

